baseURL = "https://SeeKT.github.io/portfolio/"
canonifyurls = true
languageCode = "jp"
DefaultContentLanguage = "jp"
title = "立ち話"
theme = "anatole"
publishdir = "docs"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"
